### PR TITLE
Added option for extensions

### PR DESCRIPTION
**Pull request by chrisblossom**
Added the option to specify extensions and to create output directory (only works one deep) if it does not exist.

### CODE REVIEW

**Comment by chrisblossom** [comment]
@gajus I am new to pull requesting in open source projects. Please let me know if there is something wrong with this. I will modify as requested.

**Comment by gajus** [comment]
Which issue is this PR for?

**Comment by gajus** [comment]
I am assuming it is this one https://github.com/gajus/write-file-webpack-plugin/issues/2.

**Comment by chrisblossom** [comment]
#2 and https://github.com/gajus/react-css-modules/issues/51#issuecomment-155736644

This does not solve the "does not handle assets that were not part of a chunk" concern of #2.

**Comment by gajus** [comment]
Closed in favour of a v2 https://github.com/gajus/write-file-webpack-plugin/commit/8758365810069b4fac3e8654cc8164157687842b

**Pull request closed without merging**
